// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6iZ0nMhCqH0EuuWqqGhtFe-UquaZozDw',
    appId: '1:1002727750914:web:8d590682da3f04d667161b',
    messagingSenderId: '1002727750914',
    projectId: 'simplenotes-e-ab-flutter-proj',
    authDomain: 'simplenotes-e-ab-flutter-proj.firebaseapp.com',
    storageBucket: 'simplenotes-e-ab-flutter-proj.firebasestorage.app',
    measurementId: 'G-LTEVZZ7JYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd4ZjzoConI2Ulq-twu0WTKwjb-XY94QI',
    appId: '1:1002727750914:android:1eeac02aa3366a1d67161b',
    messagingSenderId: '1002727750914',
    projectId: 'simplenotes-e-ab-flutter-proj',
    storageBucket: 'simplenotes-e-ab-flutter-proj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs6xmWrIKAQWx5o9M0F1Q7QYvoMKyWXm0',
    appId: '1:1002727750914:ios:96b7efc7cd5da69b67161b',
    messagingSenderId: '1002727750914',
    projectId: 'simplenotes-e-ab-flutter-proj',
    storageBucket: 'simplenotes-e-ab-flutter-proj.firebasestorage.app',
    iosBundleId: 'com.elgarsabolins.simplenotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs6xmWrIKAQWx5o9M0F1Q7QYvoMKyWXm0',
    appId: '1:1002727750914:ios:96b7efc7cd5da69b67161b',
    messagingSenderId: '1002727750914',
    projectId: 'simplenotes-e-ab-flutter-proj',
    storageBucket: 'simplenotes-e-ab-flutter-proj.firebasestorage.app',
    iosBundleId: 'com.elgarsabolins.simplenotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6iZ0nMhCqH0EuuWqqGhtFe-UquaZozDw',
    appId: '1:1002727750914:web:91a852ce1e1bc14067161b',
    messagingSenderId: '1002727750914',
    projectId: 'simplenotes-e-ab-flutter-proj',
    authDomain: 'simplenotes-e-ab-flutter-proj.firebaseapp.com',
    storageBucket: 'simplenotes-e-ab-flutter-proj.firebasestorage.app',
    measurementId: 'G-XKTSZQX38R',
  );
}
