// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEY7TwOK55LNh1q3gRfcnBgTgkETbxm7g',
    appId: '1:560379676148:web:b58bb1166012bb6735e5a1',
    messagingSenderId: '560379676148',
    projectId: 'todolist-flutter-e-ab',
    authDomain: 'todolist-flutter-e-ab.firebaseapp.com',
    storageBucket: 'todolist-flutter-e-ab.firebasestorage.app',
    measurementId: 'G-DVGB502WGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR3sN-tK4PnYXhkA0rktgU1NBUq4-YkXg',
    appId: '1:560379676148:android:1c8216217c09064235e5a1',
    messagingSenderId: '560379676148',
    projectId: 'todolist-flutter-e-ab',
    storageBucket: 'todolist-flutter-e-ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGSfRBrty9HL0VAjwtaUTa17tTbvQRFro',
    appId: '1:560379676148:ios:8e3ba785c1f0b14435e5a1',
    messagingSenderId: '560379676148',
    projectId: 'todolist-flutter-e-ab',
    storageBucket: 'todolist-flutter-e-ab.firebasestorage.app',
    iosBundleId: 'com.elgarsabolins.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGSfRBrty9HL0VAjwtaUTa17tTbvQRFro',
    appId: '1:560379676148:ios:8e3ba785c1f0b14435e5a1',
    messagingSenderId: '560379676148',
    projectId: 'todolist-flutter-e-ab',
    storageBucket: 'todolist-flutter-e-ab.firebasestorage.app',
    iosBundleId: 'com.elgarsabolins.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEY7TwOK55LNh1q3gRfcnBgTgkETbxm7g',
    appId: '1:560379676148:web:e22ecebc99c5e4cf35e5a1',
    messagingSenderId: '560379676148',
    projectId: 'todolist-flutter-e-ab',
    authDomain: 'todolist-flutter-e-ab.firebaseapp.com',
    storageBucket: 'todolist-flutter-e-ab.firebasestorage.app',
    measurementId: 'G-JS03J38KKF',
  );

}